### ISSUE TITLE
Unable to load the "openclimatefix/goes-mrms" dataset

### ISSUE THREAD

**Issue by codeastra2** [openclimatefix/metnet#23]
**Describe the bug**
Unable to the load the dataset, since the file `goes-mrms.py`  is not present. 
![image](https://user-images.githubusercontent.com/16428095/156937619-79f644c5-e564-433f-be83-2842ccdd9076.png)

**To Reproduce**
1. Clone the dataset and install the requirements as specified. 
2. Upon trying to load the dataset this error occurs. 

**Additional context**
1. huggingface-hub==0.4.0

**Comment by jacobbieker** [comment]
Hi, yeah, sorry, the dataset has been taking longer to prepare, so it hasn't been finished yet and ready to download, I added a note on the README for it, but am hoping to have it up soonish! The MRMS data is just taking a long time to process.

**Comment by daniellefisla** [comment]
Hi, any update on this?

Thx

**Comment by Lewisbarbara** [comment]
Hi, are there any datasets similar to the one used for METNET that I can try?

**Comment by jacobbieker** [comment]
Hi, sorry, we never got around to getting the whole dataset together. To have a similar one, you can use the Planetary Computer though, it has the MRMS data and GOES imagery, so you can stream it in from there.
