### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/metnet#58]
Currently the CI is failing, probably should fix these

**Comment by rahul-maurya11b** [comment]
fixed from #64  and premmit.ci is also fixed in my forked repo. 

![image](https://github.com/openclimatefix/metnet/assets/98907006/304fdc8d-09ae-4d63-940f-311f72828f22)

**Comment by jacobbieker** [comment]
Tests are fixed with #64
