### ISSUE TITLE
Look into "MetNet-2"

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/metnet#6]
MetNet-2:  https://ai.googleblog.com/2021/11/metnet-2-deep-learning-for-12-hour.html

Some notes about MetNet-2:

* Probabilistic prediction of rainfall up to 12 hours ahead.
* _Simpler_ model than MetNet-1.  MetNet-2 has no attention layers.  "Just" ConvLSTM and dilated conv.  (They say they had to simplify the model to enable them to use a huge geospatial area of context of 2048<sup>2</sup> km<sup>2</sup>)
* This is a _big_ model:  "the model is distributed across 128 cores of a Cloud TPU v3-128"
* Looks like there's no cross-fertilisation between "Google's MetNet" team and "DeepMind's nowcasting" team :slightly_smiling_face: 

Hat tip to @jacobbieker for spotting Google AI's blog post about MetNet-2!

**Comment by jacobbieker** [comment]
Just reading through the paper a bit more, they also give it NWP initial state, and the last hour of on the ground rainfall measurements, and it predicts instantaneous rainfall measure and cumulated measure at 2 and 60min intervals. They also give a variant the NWPs of future lead times, just like what we are doing! They use 612 variables, including oceanic variables, and at various altitudes in the atmosphere.

The lead time conditioning is also a bit more involved than the original MetNet. They do add the one-hot embedding to the input, it is also applied an additive and multiplicative factor to each of the convolutional layers in MetNet-2. 

They also go a bit into the physics a bit, and have some nice plots of attribution of each input pixel for each channel of the input data to the final predicted pixel value

**Comment by jacobbieker** [comment]
i.e. some of the GOES satellite channels are only used for nowcasting in the model, and don't affect longer forecasts, etc.

**Comment by manikbali** [comment]
In addition to the NWP initialization, they use the dominant predictors from sources such as GOES images to generate the likelihood and subsequently interpolate the parameters of the likelihood over the uniform grid and then get the probability of precipitation. Similar approaches are widely used in statistical downscaling, and precipitation regriding and gives good results in areas where station data good.  But would have lower skills on dry wet transition zones and low density of station data.
